name: Portfolio deployment

on:
  push:
    branches: [main]
    
    workflow_dispatch:

jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Build
      run: echo Building the app
    
    # deploy dev
    deploy-devlopment:
      runs-on: ubuntu-latest
      enviroment:
        name: dev
        url: ${{vars.URL}}
      needs: build
      steps:
        - name: Repo Checkout
          uses: actions/checkout@v1
        - name: Hostinger deployment
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{secrets.SERVER_SHH_KEY}}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "public/"
            REMOTE_HOST: ${{vars.REMOTE_HOST}}
            REMOTE_USER: ${{vars.REMOTE_USER}}
            REMOTE_PORT: ${{vars.REMOTE_PORT}}
            TARGET: ${{vars.TARGET}}

   # deploy staging
    deploy-staging:
      runs-on: ubuntu-latest
      enviroment: 
        name: stage
        url: ${{vars.URL}}
      needs: deploy-dev
      steps:
        - name: Repo Checkout
          uses: actions/checkout@v1
        - name: Hostinger deployment
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{secrets.SERVER_SHH_KEY}}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "public/"
            REMOTE_HOST: ${{vars.REMOTE_HOST}}
            REMOTE_USER: ${{vars.REMOTE_USER}}
            REMOTE_PORT: ${{vars.REMOTE_PORT}}
            TARGET: ${{vars.TARGET}}

     # deploy prod
    deploy-staging:
      runs-on: ubuntu-latest
      enviroment: 
        name: prod
        url: ${{vars.URL}}
      needs: deploy-stage
      steps:
        - name: Repo Checkout
          uses: actions/checkout@v1
        - name: Hostinger deployment
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{secrets.SERVER_SHH_KEY}}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "public/"
            REMOTE_HOST: ${{vars.REMOTE_HOST}}
            REMOTE_USER: ${{vars.REMOTE_USER}}
            REMOTE_PORT: ${{vars.REMOTE_PORT}}
            TARGET: ${{vars.TARGET}}